import { Product, Service } from "./types";

export const services: Service[] = [
  {
    id: 1,
    title: "Electronics Distribution",
    description: "Access to 500+ leading manufacturers with competitive pricing, real-time inventory, and same-day shipping across Florida and the Southeast.",
    icon: "Truck",
    features: ["500+ Authorized Lines", "Real-time Stock Visibility", "Same-Day Shipping", "Volume Pricing"],
    image: "/images/distribution.jpg",
  },
  {
    id: 2,
    title: "Design Win Support",
    description: "Our expert FAEs partner with your engineers from concept through production, providing technical guidance, sample support, and lifecycle recommendations.",
    icon: "Lightbulb",
    features: ["Dedicated Field Engineers", "Reference Designs", "Sample Program", "Lifecycle Management"],
    image: "/images/components.jpg",
  },
  {
    id: 3,
    title: "Supply Chain Solutions",
    description: "Comprehensive inventory management, VMI programs, and demand forecasting to reduce lead times and optimize your working capital.",
    icon: "BarChart3",
    features: ["Vendor Managed Inventory", "Kanban & JIT Programs", "Obsolescence Monitoring", "Custom Forecasting"],
  },
  {
    id: 4,
    title: "Value-Added Services",
    description: "Custom kitting, programming, tape & reel, and quality inspection services performed in our Florida facilities to your exact specifications.",
    icon: "Package",
    features: ["Custom Kitting & Labeling", "Device Programming", "Tape & Reel Services", "Incoming Inspection"],
    image: "/images/services-ems.jpg",
  },
];

export const products: Product[] = [
  {
    id: 1,
    name: "TMS320F28379D Microcontroller",
    category: "Semiconductors",
    manufacturer: "Texas Instruments",
    sku: "TI-F28379D-01",
    description: "High-performance 32-bit floating-point microcontroller for industrial control and automation applications.",
    specs: "200 MHz | 1MB Flash | 204KB RAM | 16-bit ADC",
    image: "/images/product-microchip.jpg",
    leadTime: "2-4 weeks",
  },
  {
    id: 2,
    name: "GRM188R61E106MA73D Multilayer Ceramic Capacitor",
    category: "Passives",
    manufacturer: "Murata",
    sku: "MUR-106MA73D-100",
    description: "10µF 25V X5R 0603 ceramic capacitor, ideal for decoupling and filtering in high-density designs.",
    specs: "10 µF | 25 V | X5R | 0603 | ±20%",
    image: "/images/product-passives.jpg",
    leadTime: "1-2 weeks",
  },
  {
    id: 3,
    name: "Micro-Fit 3.0 Connector System",
    category: "Connectors",
    manufacturer: "Molex",
    sku: "MOL-43045-0412",
    description: "3.00mm pitch wire-to-board and wire-to-wire connector system for power and signal applications.",
    specs: "4 Circuits | 8.5A | Through Hole | Tin Plated",
    image: "/images/product-connectors.jpg",
    leadTime: "1 week",
  },
  {
    id: 4,
    name: "ADXL355 Low Noise 3-Axis MEMS Accelerometer",
    category: "Semiconductors",
    manufacturer: "Analog Devices",
    sku: "ADI-XL355B-01",
    description: "Low power, low noise 3-axis accelerometer with digital output for precision industrial sensing.",
    specs: "±2/4/8g | 1.3µg/√Hz | SPI/I2C | -40°C to +125°C",
    image: "/images/product-microchip.jpg",
    leadTime: "3-5 weeks",
  },
  {
    id: 5,
    name: "ERJ-P Series High Power Chip Resistors",
    category: "Passives",
    manufacturer: "Panasonic",
    sku: "PAN-ERJP6W-100",
    description: "High reliability thick film chip resistors with superior power handling and pulse withstand capability.",
    specs: "0.25W | 100Ω | 1206 | ±1% | AEC-Q200",
    image: "/images/product-passives.jpg",
    leadTime: "1-2 weeks",
  },
  {
    id: 6,
    name: "M12 A-Code Circular Connectors",
    category: "Connectors",
    manufacturer: "TE Connectivity",
    sku: "TE-1-2273024-1",
    description: "Rugged M12 circular connectors for industrial Ethernet, sensors, and harsh environment applications.",
    specs: "5 Position | IP67 | A-Code | Panel Mount",
    image: "/images/product-connectors.jpg",
    leadTime: "2 weeks",
  },
  {
    id: 7,
    name: "STM32H7 High Performance MCU",
    category: "Semiconductors",
    manufacturer: "STMicroelectronics",
    sku: "STM-H743VI-01",
    description: "Arm Cortex-M7 based microcontroller with advanced graphics and connectivity for demanding embedded systems.",
    specs: "480 MHz | 2MB Flash | 1MB RAM | LQFP100",
    image: "/images/product-microchip.jpg",
    leadTime: "4-6 weeks",
  },
  {
    id: 8,
    name: "IHLP Series Low Profile Power Inductors",
    category: "Passives",
    manufacturer: "Vishay",
    sku: "VIS-IHLP5050-100",
    description: "Shielded high current inductors for DC/DC converters and power management in space-constrained designs.",
    specs: "10 µH | 12A | 12.9x13.2mm | 20% Tol",
    image: "/images/product-passives.jpg",
    leadTime: "1 week",
  },
];

export const categories = ["All", "Semiconductors", "Passives", "Connectors"] as const;

export const companyInfo = {
  name: "Blue Water Components",
  tagline: "Precision Components. Reliable Partnerships.",
  location: "Tampa Bay, Florida",
  phone: "(813) 555-0192",
  email: "sales@bluewatercomponents.com",
  address: "12450 Corporate Blvd, Suite 300\nTampa, FL 33637",
  hours: "Monday – Friday: 7:30am – 5:30pm EST",
};
